### ISSUE TITLE
Turn Server and Parameters

### ISSUE THREAD

**Issue by PascalPflaum** [simplewebrtc/signalmaster#22]
Hi, i would like to know, which turn server you recommend?

I tested it with https://code.google.com/p/rfc5766-turn-server/
and it seems to work quite well.

I noticed in the server.js code a passage about a single pre-shared-key and timestamp-based usernames. Would you mind sharing your turn server configuration to use this pre-shared key?

Or did i fully misunderstood the security concept of TURN and it is just required that both p2p clients have a hmac based on the same shared key?

**Comment by Hirtenknogger** [comment]
@fippo i have problems with the preshared key. Can you reshare your config file?
